In [1]:
import torch
import torch.nn.functional as F
from torch import nn 

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self,X):
        return X - X.mean()
layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net =  nn.Sequential(nn.Linear(8,128),CenteredLayer())
Y = net(torch.rand(4,8))
Y.mean()

tensor(3.7253e-09, grad_fn=<MeanBackward0>)

In [4]:
class MyLinear(nn.Module):
    def __init__(self,in_units,units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units,units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self,X):
        linear = torch.matmul(X,self.weight.data) + self.bias.data
        return F.relu(linear)
dense = MyLinear(5,3)
dense.weight

Parameter containing:
tensor([[-0.2315, -0.3375, -0.3162],
        [ 1.3153, -0.2711, -0.2428],
        [-0.5914,  1.2323, -0.8683],
        [-0.2372,  0.9099, -0.6128],
        [-0.2061, -0.9805, -0.0288]], requires_grad=True)

In [5]:
dense(torch.rand(2,5))

tensor([[1.0368, 1.3036, 0.0000],
        [1.2892, 0.6900, 0.0000]])

In [7]:
net = nn.Sequential(MyLinear(64,8),MyLinear(8,1))
net(torch.rand(2,64))

tensor([[0.0000],
        [0.4190]])