In [1]:
import torch

In [2]:
x = torch.arange(12)

print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [6]:
X = x.reshape(3,4)

In [7]:
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [8]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((3,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [17]:
k = torch.tensor([[[2,1,4,3],[4,3,2,1],[1,2,3,4]],[[2,1,4,3],[4,3,2,1],[1,2,3,4]]])

In [18]:
print(k)

tensor([[[2, 1, 4, 3],
         [4, 3, 2, 1],
         [1, 2, 3, 4]],

        [[2, 1, 4, 3],
         [4, 3, 2, 1],
         [1, 2, 3, 4]]])


In [19]:
k.shape

torch.Size([2, 3, 4])

In [25]:
x = torch.tensor([0,1.0,2,4,8])
y = torch.tensor([2,2,2,2,3])
x+y,x-y,x*y,x/y,x**y

(tensor([ 2.,  3.,  4.,  6., 11.]),
 tensor([-2., -1.,  0.,  2.,  5.]),
 tensor([ 0.,  2.,  4.,  8., 24.]),
 tensor([0.0000, 0.5000, 1.0000, 2.0000, 2.6667]),
 tensor([  0.,   1.,   4.,  16., 512.]))

In [26]:
torch.exp(x) # e的多少次方

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [40]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2,1,4,3],[4,3,2,1],[1,2,3,4]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 4.,  3.,  2.,  1.],
         [ 1.,  2.,  3.,  4.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  4.,  3.,  2.,  1.],
         [ 8.,  9., 10., 11.,  1.,  2.,  3.,  4.]]))

In [35]:
X == Y

tensor([[False,  True, False,  True],
        [ True, False, False, False],
        [False, False, False, False]])

In [36]:
X.sum()

tensor(66.)

In [41]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [42]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [45]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [47]:
X[1,2] = 9

In [48]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [49]:
X[0:2,:] = 12

In [50]:
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [51]:
before = id(Y)
Y = Y+X
id(Y) == before

False

In [54]:
Z = torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:] = X + Y
print('id(Z):',id(Z))


id(Z): 135628264837904
id(Z): 135628264837904


In [55]:
before = id(X)
X +=Y
id(X) == before

True

In [57]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [58]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)