In [2]:
import torch

In [10]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [11]:
x.requires_grad_(True)
x.grad

In [12]:
y = 2 * torch.dot(x,x) # dot点积
y

tensor(28., grad_fn=<MulBackward0>)

In [13]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [14]:
x.grad == 4 * x

tensor([True, True, True, True])

In [15]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [16]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [17]:
x.grad.zero_()
y = x * x 
u = y.detach()
z = u * x
z.sum().backward()
x.grad == u 

tensor([True, True, True, True])

In [18]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [22]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b 
    else:
        c = 100 * b
    return c
a = torch.randn(size=(),requires_grad=True)
d = f(a)
d.backward()
a.grad == d / a

tensor(False)