In [4]:
import torch

In [27]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [28]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [29]:
x[3]

tensor(3)

In [30]:
len(x)

4

In [32]:
x.shape

torch.Size([4])

In [33]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [34]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [35]:
B =torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [36]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [37]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [6]:
A = torch.arange(20*2,dtype=torch.float32).reshape(2,5,4)
B = A.clone()
B,A+B

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[[ 0.,  2.,  4.,  6.],
          [ 8., 10., 12., 14.],
          [16., 18., 20., 22.],
          [24., 26., 28., 30.],
          [32., 34., 36., 38.]],
 
         [[40., 42., 44., 46.],
          [48., 50., 52., 54.],
          [56., 58., 60., 62.],
          [64., 66., 68., 70.],
          [72., 74., 76., 78.]]]))

In [7]:
A * B

tensor([[[0.0000e+00, 1.0000e+00, 4.0000e+00, 9.0000e+00],
         [1.6000e+01, 2.5000e+01, 3.6000e+01, 4.9000e+01],
         [6.4000e+01, 8.1000e+01, 1.0000e+02, 1.2100e+02],
         [1.4400e+02, 1.6900e+02, 1.9600e+02, 2.2500e+02],
         [2.5600e+02, 2.8900e+02, 3.2400e+02, 3.6100e+02]],

        [[4.0000e+02, 4.4100e+02, 4.8400e+02, 5.2900e+02],
         [5.7600e+02, 6.2500e+02, 6.7600e+02, 7.2900e+02],
         [7.8400e+02, 8.4100e+02, 9.0000e+02, 9.6100e+02],
         [1.0240e+03, 1.0890e+03, 1.1560e+03, 1.2250e+03],
         [1.2960e+03, 1.3690e+03, 1.4440e+03, 1.5210e+03]]])

In [8]:
a = 2
X= torch.arange(24).reshape(2,3,4)
a +X,(a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [9]:
x = torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [10]:
A.shape,A.sum()

(torch.Size([2, 5, 4]), tensor(780.))

In [11]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0,A_sum_axis0.shape

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 torch.Size([5, 4]))

In [13]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1,A_sum_axis1.shape

(tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([2, 4]))

In [22]:
demo=A.sum(axis=[2])
A,A.shape,demo,demo.shape

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 torch.Size([2, 5, 4]),
 tensor([[  6.,  22.,  38.,  54.,  70.],
         [ 86., 102., 118., 134., 150.]]),
 torch.Size([2, 5]))

In [23]:
A.mean(),A.sum()/A.numel()

(tensor(19.5000), tensor(19.5000))

In [25]:
A,A.mean(axis=0),A.sum(axis=0)/A.shape[0]

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]))

In [28]:
sum_A = A.sum(axis=0,keepdims=True)
sum_A

tensor([[[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

In [29]:
A / sum_A

tensor([[[0.0000, 0.0455, 0.0833, 0.1154],
         [0.1429, 0.1667, 0.1875, 0.2059],
         [0.2222, 0.2368, 0.2500, 0.2619],
         [0.2727, 0.2826, 0.2917, 0.3000],
         [0.3077, 0.3148, 0.3214, 0.3276]],

        [[1.0000, 0.9545, 0.9167, 0.8846],
         [0.8571, 0.8333, 0.8125, 0.7941],
         [0.7778, 0.7632, 0.7500, 0.7381],
         [0.7273, 0.7174, 0.7083, 0.7000],
         [0.6923, 0.6852, 0.6786, 0.6724]]])

In [34]:
d=A.cumsum(axis=1)
A,d

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]),
 tensor([[[  0.,   1.,   2.,   3.],
          [  4.,   6.,   8.,  10.],
          [ 12.,  15.,  18.,  21.],
          [ 24.,  28.,  32.,  36.],
          [ 40.,  45.,  50.,  55.]],
 
         [[ 20.,  21.,  22.,  23.],
          [ 44.,  46.,  48.,  50.],
          [ 72.,  75.,  78.,  81.],
          [104., 108., 112., 116.],
          [140., 145., 150., 155.]]]))

In [35]:
y = torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [36]:
torch.sum(x*y)

tensor(6.)

In [43]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [44]:
B = torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [45]:
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [46]:
torch.abs(u).sum()

tensor(7.)

In [49]:
torch.ones((4,9)
           torch.norm(torch.ones((4,9)))

SyntaxError: '(' was never closed (85516247.py, line 1)